name: C Program CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up GCC (if not using a Makefile)
      run: sudo apt-get install gcc  

    - name: Compile C program
      run: gcc -o spellcheck main.c dict_lib.c  

    - name: Run tests
      run: ./spellcheck test.txt  

    - name: Clean up (optional)
      run: rm spellcheck  