name: Testing Program

on:
  push: 
    branches:
      - main
  pull_request: # Trigger the workflow when a pull request is created or updated.

jobs:
  build-and-test: # The name of the job.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install GCC compiler and necessary tools
      - name: Install GCC and DiffUtils
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc diffutils

      # Step 3: Compile the testing program
      - name: Build the program
        run: gcc -o testing test_code.c Dict_lib.c

      # Step 4: Run the testing program with the test dataset and capture the output
      - name: Run the test
        run: |
          ./testcode.exe testdataset.txt 

      # Step 5: Check for test failures
      - name: Check test result # Fail the job if the test results are not as expected.
        if: failure() # This step runs only if the previous step (Run the test) fails.
        run: exit 1 # Explicitly fails the job by exiting with a non-zero status code.