name: Test Spellcheck Program 

on:
  push: 
    branches:
      - main 
  pull_request: # Trigger the workflow when a pull request is created or updated.

jobs:
  build-and-test: # The name of the job.
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code 
        uses: actions/checkout@v3 

      # Step 2: Install GCC compiler
      - name: Install GCC 
        run: sudo apt-get install -y gcc 

      # Step 3: Compile the test_code program
      - name: Build the program 
        run: gcc -o spellcheck test_code.c dict_lib.c 

      # Step 4: Run the spellcheck program with a test dataset
      - name: Run the test 
        run: ./spellcheck testdataset.txt 

      # Step 5: Check for test failures
      - name: Check test result # Fail the job if the test results are not as expected.
        if: failure() # This step runs only if the previous step (Run the test) fails.
        run: exit 1 # Explicitly fails the job by exiting with a non-zero status code.
